# Generated by Django 3.2.6 on 2021-08-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('photo_link', models.TextField(verbose_name='Ссылка на картинку товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('description', models.TextField(null=True, verbose_name='Описание товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Телеграм ID пользователя')),
                ('referrer_id', models.BigIntegerField(verbose_name='Телеграм ID пригласившего')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя пользователя')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Юзернейм пользователя')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Адресс электронной почты пользователя')),
            ],
            options={
                'verbose_name': 'Пользоатель',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(verbose_name='Размер скидки')),
                ('telegram_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.discounts', unique=True)),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
    ]
